name: Maven build

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
  deploy:
    needs: build-java
    runs-on: ubuntu-latest

    steps:
      - name: CheckoutCode
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/fin-sight:latest .
          docker push ${{secrets.DOCKER_USERNAME}}/fin-sight:latest

  build-angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli

      - name: Install dependencies
        working-directory: ./fin-sight-ui
        run: npm install

      - name: Build Angular project
        working-directory: ./fin-sight-ui
        run: ng build